Update README.md
devDV/chat pull request #2
Opened 2020-07-09 13:15 UTC by torgeek

мои 4 копейки

2020-07-09 16:38 UTC, GreenSuslik commented on README.md
> +3. Под запретом слова 'власть' и 'народ' - многозначны, каждый понимает под ними что-то своё. определить что хотел сказать собеседник без контекста не представляется возможным. то есть либо глупость,
Голосуем

2020-07-09 16:38 UTC, GreenSuslik commented on README.md
> +2. Чат про айти и жизнь в айти.
Голосуем

2020-07-09 16:38 UTC, GreenSuslik commented on README.md
> +1. Вся политота в https://t.me/pr_po
Голосуем

2020-07-09 16:38 UTC, dattk commented on README.md
> +3. Под запретом слова 'власть' и 'народ' - многозначны, каждый понимает под ними что-то своё. определить что хотел сказать собеседник без контекста не представляется возможным. то есть либо глупость,
надо как-то перефразировать "глупость простительная малолетним"

2020-07-09 19:00 UTC, GreenSuslik commented on README.md
> +4. Под запретом ссылки и перепосты без личного коммента.
Голосуем

2020-07-09 22:08 UTC, darthunix requested changes
Предлагаю выкинуть из PR все пункты, кроме #2

2020-07-10 02:16 UTC, bintocher commented on README.md
> +3. Под запретом слова 'власть' и 'народ' - многозначны, каждый понимает под ними что-то своё. определить что хотел сказать собеседник без контекста не представляется возможным. то есть либо глупость,
3. Не обсуждается: политика/религия/спорт

2020-07-13 15:50 UTC, GreenSuslik commented on README.md
> +1. Вся политота в https://t.me/pr_po
```suggestion
```
Не одобрили

2020-07-13 15:50 UTC, GreenSuslik commented on README.md
> +3. Под запретом слова 'власть' и 'народ' - многозначны, каждый понимает под ними что-то своё. определить что хотел сказать собеседник без контекста не представляется возможным. то есть либо глупость,
```suggestion
```
Не одобрили

2020-07-13 15:50 UTC, GreenSuslik commented on README.md
> +4. Под запретом ссылки и перепосты без личного коммента.
```suggestion
```
Не ободрили

2020-07-14 11:47 UTC, merged